version: "3.8"

services:
  nginx:
    build: .
    container_name: nginx-fileserver
    volumes:
      - ./files:/usr/share/nginx/html/files:ro
    restart: unless-stopped

  fileserver:
    image: sigoden/dufs:latest
    container_name: dufs-fileserver
    volumes:
      - ./files:/data:rw
    command: /data -A --allow-upload -a ${DUFS_AUTH}@/:rw
    restart: unless-stopped