version: "3.8"

services:
  nginx:
    build: .
    container_name: nginx-fileserver
    volumes:
      - ./files:/usr/share/nginx/html/files:ro
    restart: unless-stopped

  fileserver:
    build: 
      context: .
      dockerfile: Dockerfile.dufs
    container_name: dufs-fileserver
    volumes:
      - ./files:/data:rw
    command: /data -A --allow-upload -a ${DUFS_AUTH}@/:rw --port 80
    restart: unless-stopped